/*
 * This file is generated by jOOQ.
*/
package gon.cue.model.ddl;


import gon.cue.model.ddl.tables.Directory;
import gon.cue.model.ddl.tables.Drelation;
import gon.cue.model.ddl.tables.Files;
import gon.cue.model.ddl.tables.Frelation;
import gon.cue.model.ddl.tables.Permisions;
import gon.cue.model.ddl.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.DIRECTORY</code>.
     */
    public static final Directory DIRECTORY = Directory.DIRECTORY;

    /**
     * The table <code>PUBLIC.DRELATION</code>.
     */
    public static final Drelation DRELATION = Drelation.DRELATION;

    /**
     * The table <code>PUBLIC.FILES</code>.
     */
    public static final Files FILES = Files.FILES;

    /**
     * The table <code>PUBLIC.FRELATION</code>.
     */
    public static final Frelation FRELATION = Frelation.FRELATION;

    /**
     * The table <code>PUBLIC.PERMISIONS</code>.
     */
    public static final Permisions PERMISIONS = Permisions.PERMISIONS;

    /**
     * The table <code>PUBLIC.USERS</code>.
     */
    public static final Users USERS = Users.USERS;
}
