/*
 * This file is generated by jOOQ.
*/
package gon.cue.model.ddl.tables.records;


import gon.cue.model.ddl.tables.Drelation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrelationRecord extends TableRecordImpl<DrelationRecord> implements Record3<Integer, Long, byte[]> {

    private static final long serialVersionUID = -695773563;

    /**
     * Setter for <code>PUBLIC.DRELATION.IDUSER</code>.
     */
    public void setIduser(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.DRELATION.IDUSER</code>.
     */
    public Integer getIduser() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.DRELATION.DID</code>.
     */
    public void setDid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.DRELATION.DID</code>.
     */
    public Long getDid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.DRELATION.PID</code>.
     */
    public void setPid(byte... value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.DRELATION.PID</code>.
     */
    public byte[] getPid() {
        return (byte[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Long, byte[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Long, byte[]> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Drelation.DRELATION.IDUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Drelation.DRELATION.DID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field3() {
        return Drelation.DRELATION.PID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIduser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getDid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component3() {
        return getPid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIduser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getDid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value3() {
        return getPid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrelationRecord value1(Integer value) {
        setIduser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrelationRecord value2(Long value) {
        setDid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrelationRecord value3(byte... value) {
        setPid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrelationRecord values(Integer value1, Long value2, byte[] value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DrelationRecord
     */
    public DrelationRecord() {
        super(Drelation.DRELATION);
    }

    /**
     * Create a detached, initialised DrelationRecord
     */
    public DrelationRecord(Integer iduser, Long did, byte[] pid) {
        super(Drelation.DRELATION);

        set(0, iduser);
        set(1, did);
        set(2, pid);
    }
}
