/*
 * This file is generated by jOOQ.
*/
package gon.cue.model.ddl.tables.records;


import gon.cue.model.ddl.tables.Frelation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FrelationRecord extends TableRecordImpl<FrelationRecord> implements Record3<Integer, Long, byte[]> {

    private static final long serialVersionUID = -273869825;

    /**
     * Setter for <code>PUBLIC.FRELATION.IDUSER</code>.
     */
    public void setIduser(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.FRELATION.IDUSER</code>.
     */
    public Integer getIduser() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.FRELATION.FID</code>.
     */
    public void setFid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.FRELATION.FID</code>.
     */
    public Long getFid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.FRELATION.PID</code>.
     */
    public void setPid(byte... value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.FRELATION.PID</code>.
     */
    public byte[] getPid() {
        return (byte[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Long, byte[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Long, byte[]> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Frelation.FRELATION.IDUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Frelation.FRELATION.FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field3() {
        return Frelation.FRELATION.PID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIduser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component3() {
        return getPid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIduser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value3() {
        return getPid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FrelationRecord value1(Integer value) {
        setIduser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FrelationRecord value2(Long value) {
        setFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FrelationRecord value3(byte... value) {
        setPid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FrelationRecord values(Integer value1, Long value2, byte[] value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FrelationRecord
     */
    public FrelationRecord() {
        super(Frelation.FRELATION);
    }

    /**
     * Create a detached, initialised FrelationRecord
     */
    public FrelationRecord(Integer iduser, Long fid, byte[] pid) {
        super(Frelation.FRELATION);

        set(0, iduser);
        set(1, fid);
        set(2, pid);
    }
}
