/*
 * This file is generated by jOOQ.
*/
package gon.cue.model.ddl.tables;


import gon.cue.model.ddl.Indexes;
import gon.cue.model.ddl.Keys;
import gon.cue.model.ddl.Public;
import gon.cue.model.ddl.tables.records.DirectoryRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Directory extends TableImpl<DirectoryRecord> {

    private static final long serialVersionUID = 414388257;

    /**
     * The reference instance of <code>PUBLIC.DIRECTORY</code>
     */
    public static final Directory DIRECTORY = new Directory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DirectoryRecord> getRecordType() {
        return DirectoryRecord.class;
    }

    /**
     * The column <code>PUBLIC.DIRECTORY.ID</code>.
     */
    public final TableField<DirectoryRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.DIRECTORY.DNAME</code>.
     */
    public final TableField<DirectoryRecord, String> DNAME = createField("DNAME", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.DIRECTORY.DPARENT</code>.
     */
    public final TableField<DirectoryRecord, Long> DPARENT = createField("DPARENT", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.DIRECTORY.DOWNER</code>.
     */
    public final TableField<DirectoryRecord, Integer> DOWNER = createField("DOWNER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.DIRECTORY</code> table reference
     */
    public Directory() {
        this(DSL.name("DIRECTORY"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.DIRECTORY</code> table reference
     */
    public Directory(String alias) {
        this(DSL.name(alias), DIRECTORY);
    }

    /**
     * Create an aliased <code>PUBLIC.DIRECTORY</code> table reference
     */
    public Directory(Name alias) {
        this(alias, DIRECTORY);
    }

    private Directory(Name alias, Table<DirectoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private Directory(Name alias, Table<DirectoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_6);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DirectoryRecord, Long> getIdentity() {
        return Keys.IDENTITY_DIRECTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DirectoryRecord> getPrimaryKey() {
        return Keys.DIRECTORY_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DirectoryRecord>> getKeys() {
        return Arrays.<UniqueKey<DirectoryRecord>>asList(Keys.DIRECTORY_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Directory as(String alias) {
        return new Directory(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Directory as(Name alias) {
        return new Directory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Directory rename(String name) {
        return new Directory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Directory rename(Name name) {
        return new Directory(name, null);
    }
}
